#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#
nohup java -Djetty.host=${OPENSHIFT_INTERNAL_IP} -Djetty.port=${OPENSHIFT_INTERNAL_PORT} -DDATABASE_URL=postgres://${OPENSHIFT_DB_USERNAME}:${OPENSHIFT_DB_PASSWORD}@${OPENSHIFT_DB_HOST}/${OPENSHIFT_GEAR_NAME} -jar ${OPENSHIFT_REPO_DIR}target/jetty-runner-jmx.jar --port ${OPENSHIFT_INTERNAL_PORT} --config ${OPENSHIFT_REPO_DIR}src/etc/jetty.xml ${OPENSHIFT_REPO_DIR}/target/zktodo2.war > ${OPENSHIFT_LOG_DIR}server.log 2>&1 & 
